### PR TITLE
NAS-106843 / 12.1 / FC ports in target mode by default

### PR DESCRIPTION
**Pull request by william-gr**
Ticket:	NAS-106843

### CODE REVIEW

**Comment by amotin** [comment]
Role 0 is not target, it is nothing.

**Comment by william-gr** [comment]
@amotin does this need to be set to = 0? or is that the default? Should I remove these lines?

**Comment by william-gr** [comment]
@amotin ping

**Comment by amotin** [comment]
When the kernel is built with ISP_TARGET_MODE (as we do) the default is 0, so setting to 0 should not be needed.  When ISP_TARGET_MODE is not used (default FreeBSD kernel) the default is 1, that is why on FreeNAS we've had setting to 2, which is initiator, since some people just used FC disk JBODs without tuning.

**Pull request merged**
