### PR TITLE
fix(master) freenas-debug speed up and clean up

### PR DESCRIPTION
**Pull request by yocalebo**
Redmine: https://redmine.ixsystems.com/issues/30729

The vast majority of changes in this commit is to add some logic for certain services that are disabled, don't run the scripts. Exit that particular module and move on.

There are also lots of clean ups/verbiage corrections and duplicate command removals.

### CODE REVIEW

**Comment by william-gr** [comment]
@yocalebo you will need to rebase this PR on master to fix the build issue

**Comment by yocalebo** [comment]
@william-gr got it, will do

**Comment by yocalebo** [comment]
rebuild

**Comment by yocalebo** [comment]
Discussed with Timur. Built successfully. Approved.

Merging.

**Pull request merged**
