### PR TITLE
Fix freenas.json for newer versions of consul

### PR DESCRIPTION
**Pull request by jhixson74**
Ticket: #26355

### CODE REVIEW

**Comment by b-a-t** [comment]
It looks like there are both `check` and `checks` keywords in the config file. But `check` accepts only one object as a parameter, while `checks` expects array of objects. So, please, check one or another notion.

Could it be reasonable to set initial state to `passing`, as by default Consul starts with the critical state and with 2m interval we'll have it in critical for notable period.
```
"status": "passing"
```

**Comment by b-a-t** [comment]
```
Config validation failed: Error decoding '/usr/local/etc/consul.d/freenas.json': 1 error(s) decoding:

* 'Check' expected a map, got 'slice'
```

**Comment by jhixson74** [comment]
Where did you test this? What version of consul? I receive no such error. This is for master branch in the nightlies. Anything before that has an older version of consul and this will clearly fail.

**Comment by b-a-t** [comment]
You are right, I have yesterday nightly, but wrongfully tested the config with the older VM. It seems that between 0.9.x and 1.0.0 the parsing library has changed in consul.
According to the: https://github.com/hashicorp/consul/blob/d12e81860fc68956c87e3b1e88df098937a750ee/agent/config/config.go#L68-L76
now it's OK to use single map slice `[{...}]` for entries like `check` or `service`. Still, documentation on site suggests to use simple map for those.

While we are here:
> For Consul 0.9.3 and earlier you need to use enableTagOverride. Consul 1.0 supports both enable_tag_override and enableTagOverride but the latter is deprecated and will be removed in Consul 1.1.

**Pull request merged**
