### PR TITLE
feat(api): Support setting a quota on dataset

### PR DESCRIPTION
**Pull request by wido**
This allows for setting a quota when creating a dataset and return the value
afterwards.

Since datasets have no update (PUT) method yet there is no way to update the
quota through the API right now.

Signed-off-by: Wido den Hollander <wido@widodh.nl>

### CODE REVIEW

**Comment by william-gr** [comment]
Hello,

Thanks for the PR, we appreciate it, but I do have some concerns.
We are in the process of consolidating the API and GUI code, decreasing duplication.
What I would like to do here is use the ZFSDataset form for the create API, buying us the same options we have in the UI, same as we have done in c330668a9f550c8d82b7cf393ba71ef9544fd02d .

**Comment by wido** [comment]
@william-gr: Thanks for the feedback!

Didn't know that was the case, just noticed that the option was missing so I added it as I needed it.

I am running the R11 release and have mainly developed against that branch and ported to master.

What would you like to see? A PR which uses ZFSDataset for updating the dataset?

**Comment by william-gr** [comment]
Thats correct, a PR using ZFSDataset to create the dataset would be much appreciated!

**Comment by wido** [comment]
@william-gr: Ok! Let me look into that. I'll close this PR for now and pop up with a new one.

**Comment by wido** [comment]
So I've been looking into this unify of the code @william-gr and I'm a bit lost :)

Django forms are pretty new to me and I just keep hitting errors over and over. It seems that the ZFSDataset form isn't really working, correct?

Is there a way to get this PR merged in the current situation? I've been trying to unify the code for 12 hours now and I just keep getting stuck on the Django forms.

**Comment by william-gr** [comment]
I would rather not. Would you mind creating a ticket in bugs.freenas.org so I can do it then. TYVM

**Comment by wido** [comment]
Ok, I will @william-gr !

**Pull request closed without merging**
