### PR TITLE
Ensure that the update cache directory is readable by nobody, to allow

### PR DESCRIPTION
**Pull request by kithrup**
the update to work.

I tested this with FN 11.0-U1 to 11.0-U2.

Ticket: #25660

### CODE REVIEW

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
is this check failures related to jenkins issues we were seeing few days ago ? if so is it safe to merge these changes in ? Also please create a separate PR against 11.0-stable branch for this change.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Dunno about the Travis-CI issues, William can answer that

**Comment by kithrup** [comment]
There was a typo; I've fixed it and pushed it, how does it get re-re-merged?

**Comment by kmoore134** [comment]
Excellent, once the Jenkins builds come back we can go ahead and merge it here via the UI.

**Comment by kmoore134** [comment]
All tests passed! I'll click merge here, but for future merges into master you are welcome to do the honors of clicking the "Merge pull request" button yourself ;)

**Pull request merged**
