### PR TITLE
tkt-70770: Fix incorrectly ported LAGG alert

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by william-gr** [comment]
Thats to avoid false positives

**Comment by themylogin** [comment]
@william-gr In https://redmine.ixsystems.com/issues/24160 this was only happening on boot that's why I've made these changes

**Comment by william-gr** [comment]
@themylogin from what I see there is no guarantee of that. LAGG can be configured after boot, there could be some sort of race condition of LAGG setup, momentary glitch and the alert check

**Comment by themylogin** [comment]
backport

**Pull request merged**
