### PR TITLE
NAS-108154 / 12.0 / max_parallel_replication_tasks

### PR DESCRIPTION
**Pull request by themylogin**
@william-gr I am very sorry, I pushed this over a month ago but somehow forgot to create a PR. UI counterpart is not documented and implemented too, although it's only a form of one integer field.

### CODE REVIEW

**Comment by william-gr** [comment]
@themylogin we will still be missing UI side, right?

**Comment by themylogin** [comment]
Yes, that's what I've written in the first comment :(

**Comment by william-gr** [comment]
Ah missed that, sorry

**Comment by william-gr** [comment]
Do you know if there is a ticket for them?

**Comment by themylogin** [comment]
@william-gr I usually create them after we merge so they din't need to patch middleware

**Review by william-gr — APPROVED** [review]

**Comment by william-gr** [comment]
@themylogin is this OK to merge? Mostly worried about migration revs that may have changed

**Comment by themylogin** [comment]
@william-gr it's ok, we did not have any migrations since then

**Pull request merged**
