### PR TITLE
NAS-103441 / 11.3 / Exclude .system dataset from replication.list_datasets

### PR DESCRIPTION
**Pull request by themylogin**
@william-gr do you think we should do the same for iocage dataset?

### CODE REVIEW

**Comment by themylogin** [comment]
@william-gr @sonicaj problem is that if we replicate entire pool from one NAS to entire pool of another and both are using iocage, replication will fail.

**Comment by william-gr** [comment]
How? Doesnt the datasets get replicated to a sub dataset?

**Comment by sonicaj** [comment]
@themylogin to clarify, are you referring to a case where both pools have iocage activated i.e both pools already contain iocage related datasets ?

**Comment by themylogin** [comment]
> How? Doesnt the datasets get replicated to a sub dataset?

No, you can recursively replicate 192.168.0.1:tank/ -> 192.168.0.2:tank/, why not?

> @themylogin to clarify, are you referring to a case where both pools have iocage activated i.e both pools already contain iocage related datasets ?

Yes. In most common situation we have only one pool, so that's where iocage would be.

**Comment by william-gr** [comment]
That use case doesnt concern me

**Comment by sonicaj** [comment]
@themylogin i am not sure how replication handles clashes this way. If it just adds the children which are not present, functionality wise we are good. Middleware/iocage should work just fine. 

But from user point of view, maybe it would be nice if it was configurable ?

**Comment by themylogin** [comment]
@sonicaj replication won't be able to replicate iocage dataset to already existing dataset and will fail.

@william-gr got it, merging as is.

**Pull request merged**
