### PR TITLE
fix(middlewared/alert): only issue an email if uptime is lower than 3m

### PR DESCRIPTION
**Pull request by william-gr**
Ticket:	#29133
(cherry picked from commit c3a022b8720d0db0698ae450755cb562b3f84dc2)

### CODE REVIEW

**Comment by william-gr** [comment]
@themylogin I am not sure I follow the purpose. Whats the advantage over this?

**Comment by themylogin** [comment]
@william-gr middleware checks for `/tmp/middleware_started` (and creates it if it is absent). If it was absent then it was first `middlewared` startup after reboot and we may send alert. This way we can avoid magic time constants.

**Comment by william-gr** [comment]
@themylogin I dont find it magic. It is well defined in FreeBSD used everywhere, its not in python because they don't care about FreeBSD.

I would like to avoid sentinel files if at all possible, they have caused much pain already in my experience.

**Comment by themylogin** [comment]
> I dont find it magic. It is well defined in FreeBSD used everywhere, its not in python because they don't care about FreeBSD.

I meant 3 minutes. It's a magic constant. Middleware startup can easily take longer.

> I would like to avoid sentinel files if at all possible, they have caused much pain already in my experience.

This very module uses sentinel file :)

Does someone remove files from `/tmp`? I can't imagine any problems with this.

**Comment by william-gr** [comment]
@themylogin Can you do this today, then? This is time-sensitive and I have to leave for the day.

**Comment by themylogin** [comment]
@william-gr ok, 10 minutes

**Comment by william-gr** [comment]
@themylogin Please merge as soon as possible and take the redmine ticket. Thank you.

**Pull request merged**
