### PR TITLE
Modify tunable/sysctl variable name buffer to be 128 characters

### PR DESCRIPTION
**Pull request by jhixson74**
- (Quick sysctl check reveals lenghts as long as 112)

Ticket: #25336
(cherry picked from commit 521836155b79871e829d837d6ad59cb83514b765)

### CODE REVIEW

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Pull request merged**
