### PR TITLE
tkt-43196: fix(smart): Fix smart config not being regenerated when reloading smartd

### PR DESCRIPTION
**Pull request by themylogin**
Ticket: #43196

### CODE REVIEW

**Comment by themylogin** [comment]
@william-gr SystemServiceService. _update_service does reload for all services

**Comment by william-gr** [comment]
@themylogin and how is that being called on 11.1? As far as I know middleware is not used to reload anything disk wise?

**Comment by themylogin** [comment]
@william-gr problem occurs when user changes SMART threshold temperatures, middleware does update DB but does reload instead of restart and that's why smartd.conf is not updated

**Comment by william-gr** [comment]
@themylogin right, can you point me to the code updating smart threshold temperatures in 11.1 branch, please? I cant seem to be able to find it.

**Comment by william-gr** [comment]
Is that the smart.py service?

**Comment by themylogin** [comment]
https://github.com/freenas/freenas/blob/483f2061a5683f9583f4770d4f47e0d76305423f/src/middlewared/middlewared/plugins/smart.py#L40

**Pull request merged**
