### PR TITLE
Switch inadyn-mt to https://github.com/troglobit/inadyn

### PR DESCRIPTION
**Pull request by themylogin**
Ticket: #7493

### CODE REVIEW

**Comment by araujobsd** [comment]
Just as reference there is a dependency: https://github.com/freenas/ports/pull/20

**Comment by william-gr** [comment]
I am worried about breaking users using custom options without a warning.
Do you have any insight about that?

**Comment by themylogin** [comment]
@william-gr I've just figured out I can parse this options in migration using `argparse`

**Comment by william-gr** [comment]
Awesome!
This also changes the API attributes (admittedly I have neglected myself from changing it myself). 
Would you mind catching it up in the docs? (docs/api/)

Thanks!

**Pull request merged**
