### PR TITLE
Fix-14432: Jail Security - /dev/adaX disks are readable from inside a jail

### PR DESCRIPTION
**Pull request by neharathod**
In this fix, I have added a command to set the devfs ruleset over all devfs mountpoints except the host one. Hence, /dev/adaX disks are no longer readable from inside a jail.

### CODE REVIEW

**Comment by williambr** [comment]
You have yet again added several unrelated commits. Please make a PR with this single change.

**Comment by neharathod** [comment]
When I tried to push the branch I had some Non-Fast Forward errors, hence I had to pull the original branch.
I'll look into it and create a new request.

**Comment by williambr** [comment]
Just create a new branch from master and cherry-pick that change.

**Comment by neharathod** [comment]
Okay!

**Pull request closed without merging**
