### PR TITLE
NAS-104537 / 11.2 / fix race condition with sync_encrypted and volume_import methods

### PR DESCRIPTION
**Pull request by yocalebo**
@william-gr 
before this commit, I could reproduce UNIQUE constraint violation errors ~50% of the time. After this change, I couldn't get it to happen again and the database was updated accordingly via the devd event calling the `sync_encrypted` method.

### CODE REVIEW

**Comment by william-gr** [comment]
@yocalebo so if an exception occurs, whatever it is, we will have dangling entries in the database, despite the import failing?

**Comment by yocalebo** [comment]
@william-gr I don't believe so because the devd event shouldn't be triggered if we fail to import the zpool which means the entries should never be written.

**Comment by william-gr** [comment]
@yocalebo You removed code to delete all objects. Which means we will have a att least dangling Volume entry if the pool dont import. It will be seen from the UI pools list.

**Comment by yocalebo** [comment]
@william-gr Thanks, fixed it.

**Pull request merged**
