### PR TITLE
feat(middleware): pool.get_disks_for_import

### PR DESCRIPTION
**Pull request by themylogin**
Ticket: #27332

### CODE REVIEW

**Comment by themylogin** [comment]
@william-gr I've tested multipaths, everything is ok, we can merge this and it'll work as expected. However, there is one concern: frontend will likely just pass `disk.disk_name` to `import_disk` as `volume` but for multipath disks it would be incorrect (but, if I understand correctly, still working in 99.9% cases). The solution here is to pass `disk.id` to `import_disk` instead. Is importing a multipath disk a likely use case worth breaking API?

**Comment by william-gr** [comment]
@themylogin I dont think multipath is a worthy use case here.

However I dont understand how you mean this is ready to merge. How will the frontend now what to pass?
It could also be a specific partition within the disk, no?

**Comment by themylogin** [comment]
@william-gr my bad. For this to be ready to merge, we should add `include_partitions=False` argument to `get_unused` and join partition list for each disk, right? (and the partition paths would be correct even for multipath disks)

**Comment by william-gr** [comment]
@themylogin I guess that could work. If you end up doing that please also add a `@accepts()` to get_unused so UI team now how to use it from the docs.
Thanks!

**Comment by themylogin** [comment]
@william-gr done

**Pull request merged**
