### PR TITLE
NAS-105452 / 12.0 / Load openzfs-debug when booting kernel-debug

### PR DESCRIPTION
**Pull request by freqlabs**
Also removed redundant modules path variable from loader.conf.

### CODE REVIEW

**Comment by freqlabs** [comment]
@william-gr Do we generate loader.conf.local during install or will I need to keep loader.conf bootable when there is not a loader.conf.local on first boot?

**Comment by amotin** [comment]
I have got the same question. We definitely generate some tunables from the installer, for example to pass serial console settings. But I am not sure it is the same scripts, so ability of the first boot worries me too.

**Comment by amotin** [comment]
Also I don't remember whether we allow choice of debug/normal kernel from boot menu. Definitely on the first page, but any deeper? I guess debug module may be unhappy to boot with normal kernel. Is it?

**Comment by freqlabs** [comment]
Ah we can pick a debug kernel at the boot menu. That will require some customization too.

**Comment by william-gr** [comment]
loader.conf.local is not generated the same way for install, as far as I can remember loader is manipulated directly from the installer for the first time so loader.conf needs to remain bootable

**Comment by freqlabs** [comment]
I'll merge this now, but the hook isn't going to be invoked until we merge it from stable/12. I have tested by manually editing config.lua to add the hook and made sure it works as intended.

**Pull request merged**
