### PR TITLE
feat(snmp): add log level and change default to LOG_ERR

### PR DESCRIPTION
**Pull request by kmoore134**
Ticket:	#24051

Backport of fix from Master #24051

### CODE REVIEW

**Comment by william-gr** [comment]
Bad things will happen because as you can see in the build failure. There are two migration prior to that which are not in 11.0. They are pretty minor I think. I believe you could just bring the migration files 0007 and 0008 from master.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Bah, saw your comments here. I'll pull those migrations in shortly

**Comment by kmoore134** [comment]
Ok, this build looks good now. William, any other concerns?

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Pull request merged**
