### PR TITLE
Add the ability to trigger builds from pull requests

### PR DESCRIPTION
**Pull request by pkgdemon**
* This should require "Jenkins: test this please" in a comment.

### CODE REVIEW

**Comment by pkgdemon** [comment]
Jenkins: test this please

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
test

**Comment by william-gr** [comment]
Closing for now.

**Pull request closed without merging**
