### PR TITLE
Fix 27809

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by william-gr** [comment]
Please dont merge this until Monday and we can discuss this, thanks.

**Comment by themylogin** [comment]
@william-gr sure, this is only to build PR package and do integration testing

**Comment by william-gr** [comment]
@themylogin I am skeptical about using a watchdog process for middlewared.

In my opinion middlewared should not need that. If something went terribly wrong we should fix it and not mitigate it by killing the process and restarting it. That could actually make thee bug hunting more difficult since then we would have to instruct users how to stop the watchdog etc.

I believe the bug in the mentioned ticket was fixed in U1 and was caused by a "DoS" of calls to middleware subscribe of /var/log/messages file tail.

Thoughts?

**Comment by themylogin** [comment]
@william-gr I had these thoughts too. However, I came to conclusion that watchdog won't make bug hunting any more difficult. At the moment when bug occurs and watchdog times out we (if we aren't logged in to the host with `pdb`, and we are not) don't have any debugging opportunities except logs, and logs are kept after watchdog restarts our app so watchdog does not break anything. In fact, when it comes to FreeNAS, having watchdog for middleware will make bug hunting easier, because it can collect logs at the very same time when middleware has hanged. This is much better than collecting logs when user has 1) realized that his system is not responsive 2) created an issue 3) has been asked to collect logs 4) actually collected logs — at this moment they may be already rotated and we'll be struggling to find a moment when crash occurred. That was pros and cons of watchdog from developer's point of view.

What can really help is having a log of what methods have been called through WebSocket API. For RESTful application we would have web server's `access.log`, for WebSocket API we have nothing.

However, from user's point of view having watchdog only has pros. With watchdog he may not even notice that some error has happened. The worse he may experience is Web UI not working for 1-2 minutes. Think of FreeNAS as of some home appliance, e.g. router. What would you choose: a router that can lose Wi-Fi once a month for 2 minutes or a router that you will randomly have to unplug and plug back once a month because it hangs?

Sending `SIGKILL` to application may result in data loss, but again, from my experience, if `asyncio` app has hanged, it has hanged forever. I've tried to solve the issue of `asyncio` app that hanged once a week by running 4 of them behind balancer and in 4 weeks guess what has happened.

So what I think is:
 * We certainly must have watchdog that collects logs and restarts middleware. It may ask user to send these logs to us or send them automatically.
* We should not merge this into 11.1-U2. Let's test it for a while, it is a big change.
* We should add `access.log` for websocket API calls (again, not now, may be in 11.1-U3).

**Comment by william-gr** [comment]
@themylogin I dont agree entirely. We have a loop monitor which can and will help us find where event loop blocked. Its quite verbose.

Logs sometimes are not even close as being helpful to debug a problem, thats why we have `gdb`, to debug middlewared problems while they are in effect, and that will not be possible if we kill middlewared. Some problems are hard to reproduce. Thats the main reason I say it will make bug hunting more difficult.

I agree that from the user point of view it is very helpful but it can also lead to problems, the middlewared process holds several states and the amount of them will grow with time. If the process is restarted they are just lost (e.g. update download cache, clean system shutdown, applied update) and it will also interrupt long running processes like cloud sync, replication, etc.

My opinion is that If every important application needed a watchdog our operating system would be full of them, this feels like a band-aid for a bad written application.

Lets take what we have, we have released 11.0 in a while which was the first release of middlewared, I can say the number of reports because of a stuck middlewared have been pretty low, the exception and I think if we had a watchdog we would not have even heard from a good majority of them, which means we could not have fixed most of these bugs. If they don't see an issue they don't get anything to report.

I do agree with the access.log for websocket though, that seems like a fine idea.

**Comment by themylogin** [comment]
> We have a loop monitor which can and will help us find where event loop blocked. Its quite verbose.

It did not help for 27809.

> Logs sometimes are not even close as being helpful to debug a problem, thats why we have gdb, to debug middlewared problems while they are in effect, and that will not be possible if we kill middlewared. 

Are we doing `gdb` on user's FreeNAS installations?

> the middlewared process holds several states and the amount of them will grow with time. If the process is restarted they are just lost (e.g. update download cache, clean system shutdown, applied update) and it will also interrupt long running processes like cloud sync, replication, etc.

If watchdog has timed out, it means that middlewared has already hanged and has already lost it's state and long running processes are hanging too. The watchdog won't break anything here.
This also means that important states must be persisted on disk.

> My opinion is that If every important application needed a watchdog our operating system would be full of them, this feels like a band-aid for a bad written application.

Embedded devices often have watchdogs for their main applications. This does not necessarily mean they are poorly written. Modern frameworks are :) Node.js, Go, asyncio — all these technologies are meant for hipsters to develop their MVC in a month, but their software into 8 overpriced AWS instances behind balancer and secure it with supervisors and watchdogs. 99% uptime is enough for one node. No one cares for deeply-buried bugs that occur once in ages. Just make your application stateless and restart it with watchdog :(

> If they don't see an issue they don't get anything to report.

Again, we can detect these situations and report them automatically. If we would have watchdog from the start, we would have received much more automatic reports (of course, probably a lot false positives).

**Comment by william-gr** [comment]
> It did not help me for 27809.

It wasnt a problem of event loop being blocked, I am 100% sure.

> Are we doing gdb on user's FreeNAS installations?

Yes, I did that a few times.

> If watchdog has timed out, it means that middlewared has already hanged and has already lost it's state and long running processes are hanging too. The watchdog won't break anything here.
> This also means that important states must be persisted on disk.

I said that to make a point that killing middlewared does not come for free.
We cannot store important states on disk to not wear down the boot media (e.g. we cannot store on disk every time we run a replication or cloud sync. 

> Embedded devices often have watchdogs for their main applications. This does not necessarily mean they are poorly written. Modern frameworks are :) Node.js, Go, asyncio — all these technologies are meant for hipsters to develop their MVC in a month, put their software into 8 overpriced AWS instances behind balancer and secure it with supervisors and watchdogs. 99% uptime is enough for one node. No one cares for deeply-buried bugs that occur once in ages. Just make your application stateless and restart it with watchdog :(

I don't see us fitting in that scenario.

> Again, we can detect these situations and report them automatically. If we would have watchdog from the start, we would have received much more automatic reports (of course, probably a lot false positives).

Receiving reports without actual user engagement is useless. If middlewared gets to a state is completely unusable its very likely the logs will not be of any help either and the solution is to debug it deeply with gdb.

**Comment by themylogin** [comment]
> I don't see us fitting in that scenario.

and yet we use asyncio :)

Ok, you've convinced me to abandon watchdog for now. I'll create a ticket for access.log now.

**Pull request closed without merging**
