### PR TITLE
fix(API / Middleware):Fix middlewared binding to 0.0.0.0 

### PR DESCRIPTION
**Pull request by darkfiberiru**
Should bind to localhost 

Ticket: #28031

### CODE REVIEW

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Retest

**Comment by JulesRenz** [comment]
Came here to say that this change has (unfortunately) been reverted.

**Comment by dlavigne** [comment]
@Jules Renz Please create a report at bugs.ixsystems.com if it is causing an issue for you.

**Comment by JulesRenz** [comment]
@dlavigne, sorry for the late reply. I have found a [discussion on the iXsystems forums](https://www.ixsystems.com/community/threads/port-6000-tcp-open-x11-it-is-intended-any-security-problems-due-this.72570/), that I could piggyback with my concerns. 
Cheers Julian

**Pull request merged**
