### PR TITLE
[MASTER] Prior to destroy a volume we need to stop all guest vms attached to it or otherwise the volume is busy and we can't perform the action.

### PR DESCRIPTION
**Pull request by araujobsd**
Ticket: #26555

### CODE REVIEW

**Comment by william-gr** [comment]
This is also missing detecting any VMs in the volume to show to the user (check the Volume Detach dialog, please)

**Comment by araujobsd** [comment]
I'm not sure cascade delete would be a good idea when users delete the volume. We can have a guest consuming disks from different volumes, delete only the associated disk could be an option.

The best approach IMHO would be, when an user delete the volume it receives a warning about what service or subsystem is using that volume. Instead of delete everything, the user should stop the services associated with that volume. It definitely would avoid users mistakes.

**Comment by william-gr** [comment]
Cascade delete is not on by default, its an user option and has been there for several years.

That dialog shows what is in use by the volume (or good part of what is).

Deleting the associated disk seems reasonable, if the volume is destroyed the VM would probably fail to start anyway if the zvol is not there.

**Comment by araujobsd** [comment]
Now I show the VM in the dialog box and also delete the guest associated device.

**Pull request merged**
