### PR TITLE
feat(backup): Add file level encryption to the cloud sync feature

### PR DESCRIPTION
**Pull request by themylogin**
Ticket: #26924

### CODE REVIEW

**Comment by william-gr** [comment]
@themylogin  I am concerned about how we are handling encryption here.

As far as I understand we are generating the encryption every time, that means for every sync run a new random encrypted password will be used for the rclone sync operation, does that make sense or am I misunderstanding.

If thats right, files will be unrecoverable.

It also concerns me that the password is encrypted and not available to the user, both the password and the salt, that means the files will not be recoverable outside FreeNAS or if the boot device dies and that is lost.

**Comment by themylogin** [comment]
@william-gr no, we're using user-specified password and salt stored in database. 

This https://github.com/freenas/freenas/pull/534/commits/1862fbbb7c295bdc61b0caea160098456e6a0d95#diff-68be07ae3dce732fee0180335d414c03R106 is just how `rclone` encrypts passwords in it's configs.
The only thins random here is AES initialization vector (IV). It is supposed to be random. It's purpose is to a) make `crypt(password)` return different results every time and b) make `crypt(password) != crypt(pass) + crypt(word)`. Decoded password will always be the same.

**Comment by william-gr** [comment]
@themylogin I am confused:

```
>>> rclone_encrypt_password('foo')
'Sw6_62ZY672cLfpOS59wgbK66w'
>>> rclone_encrypt_password('foo')
'XaZiBrmpBjn8idM-Rb5Vv-o76A'
```

And that is called every time on `rsync`, not on password change:

```
rclone_encrypt_password(backup["encryption_password"]))
```

Wont that use a different `password` in rclone.conf every time?

**Comment by themylogin** [comment]
@william-gr It's normal (in fact, it's necessary for good encryption) for encrypted text to be different every time despite plain text being the same.

Here is code that re-implements `rclone` password encryption/decryption in python: https://gist.github.com/themylogin/3981eafc1e64e1b8f4450ecb6b24a4e6
Note that `encrypted` is always different, but `decrypted` is always `MyPassword`

**Comment by william-gr** [comment]
@themylogin sure, I know how AES works.

Your example does not reflect what I am trying to say here.

rclone uses `password` and `password2` as the encryption keys to the files sent to remote side. rclone is not aware of `key` to decrypt it password and password2 changes, right?

So how come rclone can decrypt the files if `password` and `password2` changes? middlewared will be able to decrypt whatever new `password` is generated, rclone doesn't.

Or am I missing something more fundamental here?

**Comment by themylogin** [comment]
@william-gr `key` is the key from `rclone` source https://github.com/ncw/rclone/blob/02ffd435724e344692aa4a3a36f9a0147fba888f/fs/config.go#L140 (this whole encryption schema is, `rclone` does not accept plaintext passwords from config)

**Comment by william-gr** [comment]
@themylogin ok, thats explains everything then! Knowing that `key` was rclone key was the key haha

Just one more thing, that means the user password will be stored in plaintext in the database, right?
We should probably use notifier.pwenc_encrypt/pwenc_decrypt. Thats because customers often provide their configuration files and passwords being in plain text is a bad thing for us.

**Pull request merged**
