### PR TITLE
NAS-108749 / 21.02 / Remove HTML from alert services that do not support it. Allow HTML-only e-mails

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by william-gr — COMMENTED** [review]
Does that mean text emails will no longer be sent?

Thats not the expectation, some dinosaurs prefer to see it in plain text

**Comment by anodos325** [comment]
> Thats not the expectation, some dinosaurs prefer to see it in plain text

Hey, I resemble that remark.

**Comment by themylogin** [comment]
@william-gr 

> Does that mean text emails will no longer be sent?

No, it means that it's now possible to specify `html` and omit `text` for an e-mail, and text part will be an automatically generated markdown-ish version of HTML.
All other alert services (slack, telegram, etc.) will also receive this markdown version of alert message.

**Review by william-gr — APPROVED** [review]
Ah, I see it now. Thanks!

**Pull request merged**
