### PR TITLE
NAS-105558 / 12.0 / add ResolveHostOrIp validator

### PR DESCRIPTION
**Pull request by yocalebo**
I need a synchronous method for validating Hosts or IPs for the gluster peer API. This class does that and is directly based off the `resolve_hostname` method in the `async_validators` module (which I've also pushed a PR to fix a problem).

### CODE REVIEW

**Comment by yocalebo** [comment]
@william-gr I need a synchronous method for gluster peer API so I've created this one. This is essentially the same as `resolve_hostname` method in the `async_validators` module. However, instead of code duplication, I was going to use this class in the `async_vaildators` module since it gets put into a thread anyways.

**Comment by william-gr** [comment]
@yocalebo yes, I think this wont work out. Doesnt this hits the network trying to resolve the hostname?

It may block the event loop while validating this value. It should probably be done within the method to run this in a thread.

Let me know if I didnt get this right @themylogin @sonicaj

**Comment by yocalebo** [comment]
> 
> 
> @yocalebo yes, I think this wont work out. Doesnt this hits the network trying to resolve the hostname?
> 
> It may block the event loop while validating this value. It should probably be done within the method to run this in a thread.

Hmm, I didn't think about it when this class is called by itself. The gluster API I'm writing is wrapped in a job so it's not blocking the main event loop. I'm wondering if I should just write a validator that is local to the gluster API and use it there?

**Comment by yocalebo** [comment]
> 
> 
> Yes, it will run network in the main loop. Currently we don't have infrastructure for async validators in schema, and I can explain why I think we don't need it, so I would propose to use async validator explicitly.

Is it okay to call an async validator in synchronous function?

`
@accepts(
        blah
)
@job(lock='blah', validators=[resolve_hostanme()])
`

**Comment by themylogin** [comment]
> The gluster API I'm writing is wrapped in a job so it's not blocking the main event loop.

Event loop is common for everyone. Also, schema-level validations are performed before launching the job (so we can access sanitized arguments in `@job(lock=lambda args: ...)`), which is one of the reasons I object to have validators that perform I/O.

**Comment by themylogin** [comment]
@yocalebo `@job` does not have `validators` argument.

Guess for you very case you can just do `asyncio.run_coroutine_threadsafe(resolve_hostname(...), loop=asyncio.get_event_loop()).result()` and we'll think of more elegant way to do this if this issue rises again.

**Comment by yocalebo** [comment]
> 
> 
> @yocalebo `@job` does not have `validators` argument.
> 
> Guess for you very case you can just do `asyncio.run_coroutine_threadsafe(resolve_hostname(...), loop=asyncio.get_event_loop()).result()` and we'll think of more elegant way to do this if this issue rises again.

The `@jobs` was a typo, sorry. But thanks for the clarification. I'll close this PR.

One last thing, however, the `resolve_method` has incorrect behavior when provided a short-hand IP (i.e. 192.168) because the `gethostbyname` auto-expands that to `192.0.0.168`. I closed a PR earlier that fixes that issue. I'll push that PR again and have you review for a fix.

**Pull request closed without merging**
