### PR TITLE
NAS-107256 / 12.1 / Be prepared to receive tons of zfs deadman messages

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by yocalebo** [comment]
Do we know if a scrub causes a ZfsDeadman alert for every vdev in the zpool? Lots of our customers have 100+ vdevs so we could still have potentially `n` number of alerts in 60 seconds `n` being the count of vdevs.

**Comment by themylogin** [comment]
That'll be 100 alerts which is bad anyway, I am not sure what should we do, throttle them by pool instead? (i.e. drop random events if they occur too often)

**Comment by yocalebo** [comment]
@themylogin tough problem to solve. The reason why I ask if scrubs can cause ZfsDeadman events then I'm wondering if we simply ignore them if one is triggered on a zpool while a scrub is running.

As well as keep your timed approach.

**Comment by william-gr** [comment]
@themylogin @yocalebo how about we limit by number of events per pool in a given time?

Up to say 5 events in the last 5 minutes?

In theory these deadman events should not be happening at this pace, so getting that number of alerts (5 in 5 min) is enough to tell the user some odd is happening.
We are only seeing that many events because ZFS is misbehaving?

**Comment by yocalebo** [comment]
@william-gr do we just choose the first 5 vdevs that are generated?

**Comment by william-gr** [comment]
Thats the idea, within 5 minutes...

Even on a large system if we get that many events from deadman there is probably something else off, right? And not specific to a disk.

**Comment by yocalebo** [comment]
@william-gr I'd have to agree.

**Pull request merged**
