### PR TITLE
Bug fix for an unreferenced variable

### PR DESCRIPTION
**Pull request by sonicaj**
This commit fixes a bug where we defined a variable in a different scope and used in a different one.

### CODE REVIEW

**Comment by sonicaj** [comment]
In `elif`

**Comment by william-gr** [comment]
Also, `ldap = self.middleware.call_sync('activedirectory.config')` looks wrong, calling activedirectory ; )

**Comment by sonicaj** [comment]
`ad` changes look okay because of the keys they are being assigned to but i am far from an expert on this ;) And yup `ldap` looks wrong ;) Please advise @anodos325

**Comment by william-gr** [comment]
@anodos325 ping. Feel free to take over this PR, since you know this the most.

**Comment by anodos325** [comment]
> @anodos325 ping. Feel free to take over this PR, since you know this the most.

Sorry. Just saw this. I'll take over and remove this method and replace instances where it's being used with the proper new API calls.

**Pull request merged**
