### PR TITLE
feat(netcli): Add critical for failover dialog

### PR DESCRIPTION
**Pull request by skarekrow**
If the user wants to configure failover settings, we also ask if they want to set it critical for failover

Ticket: #26279

### CODE REVIEW

**Comment by william-gr** [comment]
Oh, and of course, just for TrueNAS and HA.

**Comment by william-gr** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
backport

**Pull request merged**
