### PR TITLE
pool.download_encryption_key 

### PR DESCRIPTION
**Pull request by themylogin**
Ticket: #26460

### CODE REVIEW

**Comment by themylogin** [comment]
I need to use `core.download` in CRUDService as stated in https://github.com/freenas/freenas/pull/401/commits/9cb3e8b393fafdc586088024c27a0da7ee4d9ae6 commit message

I also think the best place for methods like this are Mixins, not base classes

**Comment by william-gr** [comment]
@themylogin why cant you use `await self.middleware.call('core.download', ...)`?

**Comment by themylogin** [comment]
@william-gr I had no idea I can do that, ok, I'll fix my PR

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Pull request merged**
