### PR TITLE
fix(notifier): check if pool imported after failed "zpool import"

### PR DESCRIPTION
**Pull request by william-gr**
That may happen if a dataset mount fails (readonly parent dataset).

Ticket:	#24936
(cherry picked from commit 3086abda5e41ccbf859406d3da759947e99d1736)

### CODE REVIEW

**Comment by amotin** [comment]
I am not familiar with py-libzfs, but it looks OK.

**Comment by araujobsd** [comment]
retest this please

**Comment by araujobsd** [comment]
retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by araujobsd** [comment]
retest this please

**Comment by araujobsd** [comment]
Jenkins: retest this please

**Comment by araujobsd** [comment]
Jenkins: retest this please

**Comment by william-gr** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
hmm,  truenas build is failing on this.

**Comment by william-gr** [comment]
Its not related to this change.

**Pull request merged**
