### PR TITLE
NAS-107789 / 20.10 / reporting.realtime interface speeds

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by william-gr — COMMENTED** [review]
Thoughts on having how much of the total utilization?

Say the link is 80% saturated/

**Comment by themylogin** [comment]
Can't they divide two numbers themselves? :)

**Comment by william-gr** [comment]
@beanpole135 thoughts? Does this work well enough for you?

**Comment by beanpole135** [comment]
I am fine with it reporting the current/max speeds, and then we can calculate the percentage ourselves.
The original reason I asked for the percentage is so that this API is not returning the same static info (max speeds for each interface) for every data interval sent out. That just seemed like a waste when you could return the dynamic percentage instead (which is typically a smaller number and reduces the data transfer - albeit only a small amount)

**Review by william-gr — APPROVED** [review]

**Comment by themylogin** [comment]
backport

**Pull request merged**
