### PR TITLE
NAS-102894 / 11.2 / Do not start NFS on HA standby node

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
@william-gr I am not sure how NFS/SMART/Asigra/etc are started on boot then, carp hook is executed on boot?

**Comment by william-gr** [comment]
Yes, carp is disabled until the end of boot process, which then triggers the carp hook script.

**Comment by william-gr** [comment]
Does this need an equivalent for 11.3 rc.conf.py?

**Comment by themylogin** [comment]
Yes, added backport label

**Pull request merged**
