### PR TITLE
NAS-108050 / 12.0 / Do not retrieve unnecessary sysctls in snmp-agent

### PR DESCRIPTION
**Pull request by themylogin**
I am not sure about the scope of this ticket, is it only to fix SNMP or also `freenas-debug/sysctl/sysctl.sh`? (it only has `sysctl -a`, I have no idea how to fix this if not in kernel)

### CODE REVIEW

**Comment by william-gr** [comment]
Can we also fix freenas debug in this PR?

**Comment by freqlabs** [comment]
I suggest sticking with `sysctl -a` in sysctl.sh and adding the few skipped kstats explicitly.
```sh
sysctl -a
for kstat in fletcher_4_bench vdev_raidz_bench dbgmsg; do
    sysctl kstat.zfs.misc.${kstat}
done
for kstat in multihost misc.state txgs; do
    for pool in $(zpool list -Ho name); do
        sysctl kstat.zfs.${pool}.${kstat}
    done
done
```
The kstats might even make more sense in the ZFS section instead, but either way works.
This gives us explicit control over the CTLFLAG_SKIP kstats we are requesting. Otherwise we end up grabbing a bunch of sysctls that are normally skipped, for example some debug sysctls for cxgbe.

**Comment by themylogin** [comment]
@freqlabs I do not understand, the point of original ticket was to remove `kstat.zfs.misc.dbufs`, but your code keeps it and just adds more sysctls?

**Comment by freqlabs** [comment]
@themylogin in the next update I am skipping these kstats by marking them with CTLFLAG_SKIP in the kernel module, so they will not be included in `sysctl -a`:

```
kstat.zfs.${pool}.multihost
kstat.zfs.${pool}.misc.state
kstat.zfs.${pool}.txgs
kstat.zfs.misc.fletcher_4_bench
kstat.zfs.misc.vdev_raidz_bench
kstat.zfs.misc.dbufs
kstat.zfs.misc.dbgmsg
```

Planning further ahead, in FreeBSD 13 `sysctl -aN` will still give the names of those skipped sysctls and many others (otherwise there is no way to find out they exist if you don't already know). That is why I recommend sticking with `sysctl -a` and adding the handful of soon-to-be-normally-skipped kstats we are interested in for ZFS.

**Review by freqlabs — APPROVED** [review]

**Review by william-gr — APPROVED** [review]

**Pull request merged**
