### PR TITLE
NAS-100045 / 11.3 / NAS-100045 PCI-E Passthrough Support for bhyve

### PR DESCRIPTION
**Pull request by stattin42**
bhyve PCI passthru support in middlewared vm plugin
ok to test

### CODE REVIEW

**Comment by freqlabs** [comment]
I imagine this same note applies to the webui PR as well, but it would be nice to permit functions in the range 0-255 instead of 0-7. This is useful for cards that use [PCIe alternative routing interpretation (ARI)] to expose additional virtual functions.

[ARI]: https://pcisig.com/sites/default/files/specification_documents/ECN-alt-rid-interpretation-070604.pdf

For example:
```
ppt7@pci0:5:0:21:	class=0x020000 card=0x00001425 chip=0x58101425 rev=0x00 hdr=0x00
    vendor     = 'Chelsio Communications Inc'
    device     = 'T580-LP-CR Unified Wire Ethernet Controller [VF]'
    class      = network
    subclass   = ethernet
    cap 10[70] = PCI-Express 2 endpoint max data 256(2048) FLR NS
                 link x0(x8) speed 0.0(8.0) ASPM disabled(L0s/L1)
    cap 11[b0] = MSI-X supports 8 messages
                 Table in map 0x20[0x0], PBA in map 0x20[0x8000]
    cap 05[50] = MSI supports 32 messages, 64 bit, vector masks
    ecap 0001[100] = AER 2 0 fatal 0 non-fatal 0 corrected
    ecap 000e[140] = ARI 1
    ecap 0017[150] = TPH Requester 1
```

**Comment by stattin42** [comment]
Code format verified with 'pycodestyle'.

**Comment by stattin42** [comment]
@themylogin, PR rebased onto fixed stable branch

**Comment by stattin42** [comment]
PR rebased onto current stable branch.

**Comment by william-gr** [comment]
Thanks @stattin42 . However we are feature frozen for 11.3. We can only implement this feature for 12 (master)

**Comment by stattin42** [comment]
Thanks @william-gr, I understand. I guess I can apply it locally or keep using vm-bhyve for 11.3. The middleware plugin can be easily patched. For the webui part I am not sure if/how I can update it on my production machine without needing to switch to nightlies. 

Anyway, I have begun porting the feature to master. Mostly done, but currently don't have a free machine to test it on. Hope to be able to fix that in a few days, and then submit a PR to 12.

**Comment by stattin42** [comment]
Feature ported to master and separate PR to master created.
Close this PR (to 11.3-stable)?

**Comment by william-gr** [comment]
Yes, thank you very much!

**Pull request closed without merging**
