### PR TITLE
NAS-108075 / 20.12 / Allow power supply alert on FREENAS-CERTIFIED

### PR DESCRIPTION
**Pull request by themylogin**
@william-gr I am not sure if this has sense to hide this alert on CORE when hardware is not FREENAS-CERTIFIED

### CODE REVIEW

**Comment by william-gr** [comment]
@darkfiberiru can you speak to any of this? Can we assume this will work for our hardware tagged as FREENAS-CERTIFIED?

**Comment by themylogin** [comment]
This was tested on fn02 (FREENAS-CERTIFIED-4U-24)

**Comment by william-gr** [comment]
Also thinking forward, are we relabeling these to TRUENAS-CERTIFIED yet?

**Comment by darkfiberiru** [comment]
Freenas certified is going away and r-series will replace it. I agree with @themylogin  I don't see reason to not have sensor visible if it's there. If no pmbus is available (method to talk to psu) those fields just don't populate in sensor list. If only one psu is inserted when bmc starts and scans bus then you insert second later the ps2 field will be missing until you reset bmc to rescan i2c bus. (Might be simpler method)

If we want to segment iX hardware and non-ix hardware as policy that fine but I don't see a technical reason to as were using a standard mechanism here. These sensors are defined by ipmi not supermicro.

**Review by william-gr — COMMENTED** [review]
We should probably add R-Series support here, then?

**Review by william-gr — APPROVED** [review]

**Review by darkfiberiru — COMMENTED** [review]
Looks good to me

**Pull request merged**
