### PR TITLE
NAS-103952 / 11.3 / Ensure objects exist before deleting them in iscsi plugin

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Comment by william-gr** [comment]
Not sure what I feel about this.

This will add a new extra query for every call.

**Comment by sonicaj** [comment]
How about passing the retrieved object to update/delete methods ?

**Comment by william-gr** [comment]
Then you want to change every single plugin to catch up with that change?

**Comment by sonicaj** [comment]
To do it correctly, yes ? An easier solution would be to make sure all update/delete have at least one `_get_instance` call ( however that would lots of duplicating lines ). If you think we should go with the latter, I'll update the PR that way

**Comment by william-gr** [comment]
We dont want to make such a huge change at this point. Just tackle the API call in question

**Comment by william-gr** [comment]
Thanks

**Comment by sonicaj** [comment]
backport

**Pull request merged**
