### PR TITLE
NAS-107146 / 12.0 / TrueNAS 12 to SCALE update

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by william-gr — APPROVED** [review]
lgtm

**Review by sonicaj — APPROVED** [review]
This looks good to me, however I am curious on how we would like to handle boot environments with the switch to scale from 12 ? I was looking into the NEP but couldn't find anything there.

**Comment by themylogin** [comment]
@sonicaj I'll handle that in `master` branch

**Comment by themylogin** [comment]
backport

**Comment by themylogin** [comment]
@william-gr I've pushed one more commit, can you please ensure if that's ok with you?

**Review by william-gr — APPROVED** [review]

**Pull request merged**
