### PR TITLE
feature: unified peer/credentials store

### PR DESCRIPTION
**Pull request by 650elx**
PR reopened + peer data model for s3

### CODE REVIEW

**Comment by 650elx** [comment]
Can we merge this?
It's a harmless piece of code that is required for the new GUI development.

**Comment by 650elx** [comment]
Actually the current form of the code is the one that we discussed and agreed upon.
It's a simple, harmless CRUD service and I'm just pushing this for the convenience of the GUI team so we can discuss mockups and simply work on this ;)

**Comment by william-gr** [comment]
Why would you need unfinished middleware code to mockup the UI? I mean, how does that help?

**Comment by 650elx** [comment]
Maybe mockup is a wrong word here because the CRUD service does not need to much discussion, although I was thinking about adding some event driven peer status indicators and it would be nice to have this in nightlies (just for their convenience) to work on this with GUI team on daily basis.

If this is a big deal then I can create a custom VM with my code in our lab. No difference for me.

**Comment by william-gr** [comment]
Sure, lets do that then! Thanks!

**Comment by 650elx** [comment]
This feature will be merged along with other replication stuff.

**Pull request closed without merging**
