### PR TITLE
Be more thorough in logging commands

### PR DESCRIPTION
**Pull request by fhriley**
All notifier.py commands are logged. The following are logged for every command:

- the file name and line number where the command was called
- the return status
- the command
- the stderr if the return status was bad.

This makes it considerably easier to debug when something goes wrong and has a side effect of reducing the amount of code needed when calling a shell command.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
This work seems rather heroic in scope, but also slightly fragile and perhaps all-too-quickly overtaken by events.  To elaborate:

1. Constructs like this:  +    libc = ctypes.cdll.LoadLibrary("libc.so.7")
Are inherently fragile in that they will break the minute FreeBSD revs the version on libc.  Possibly not going to happen anytime soon, sure, but stuff like that always makes me come up short during review.

2. In FreeNAS-10, all of the middleware has been replaced by an asynchronous daemon that logs (elaborately) everything it is asked to do and all of the replies it sends.  For a comparatively dead branch in 9.3, the question is begged:  Is it really worth potentially breaking something to instrument it to this extent?

I'm not saying this work is ill-advised, I'm just saying it begs some questions.

**Comment by fhriley** [comment]
> Constructs like this: + libc = ctypes.cdll.LoadLibrary("libc.so.7")

Not my code. I simply moved it so it wasn't being called every time a shell command was run.

> In FreeNAS-10

I was told FreeNAS-10 is over a year away. There will be people (like me) who will not be upgrading to 10 for quite some time (or ever) for fear of breaking a well running, minimal downtime appliance in the upgrade. The current logging is inadequate for diagnosing and recovering from an unexpected error. I've already found it invaluable when working with the code in my dev VM. Before this commit, I was in situations where I had no idea how to recover because not every command was logged and the gui was too confused to function. In my short time with FreeNAS, I've already seen this multiple times in the forums. 

I would hardly call this commit heroic. It looks big because I changed the shell methods to have a standard interface. All I'm doing is modifying the calls to those methods to use the new interface.

**Comment by jordanhubbard** [comment]
1. Ah, sorry, I thought your code introduced the LoadLibrary() - I will ask the author to review.
2. True, FreeNAS10 is not going to save the day anytime soon, but by the same token, people have been living with the current code literally for years, so it's hard to say that a year is going to be make-or-break time.

All that said, I will ask William to take a look since this is largely HIS code and I've never even dared to hack on notifier.py, I just had some random questions.

**Comment by jordanhubbard** [comment]
Hi Frank,

We have reviewed this again and have a request based on the following concerns:

1. We have a product, TrueNAS, which is based on FreeNAS and extends the notifier in ways specific to TrueNAS.

2. We have a lot of FreeNAS customers (tens if not hundreds of thousands) who may break if there are any issues at all with these changes, thus we would be interested in making the smallest, most conservative set of changes even in the absence of point #1 above.

So, based on that, our request is:  Can you perhaps break this pull request into two pieces, the first containing just the logging improvements alone and the other containing the rest?  We will then merge the first bit, get some testing on it, and then be able to review the refactoring separately.  Thanks!

**Comment by fhriley** [comment]
I fully understand the need to make sure no regression is added, and I expected extra scrutiny with this commit. However, I don't understand how separating the logging from the refactor would be less risky. The logging depends on the refactor, which makes the logging part only a few lines of code. If I didn't do the refactor, I'd have to add logging everywhere the refactor touched, which would result in a commit just as large as this one. I would then do the refactor, which would remove all the redundant logging that was just added and replace it with the refactored pipe call, which would result in another big commit. It would be twice the work with twice the risk.

If someone reviews the code in a side-by-side diff, they'll see this commit is really not complicated. It's mostly just changing the pipe calls from

```
p = self._pipe()
status = p.wait()
```

with 

```
status = self._pipe()[-1]
```

and the equivalent for when we need to grab the output. I reviewed the code myself several times, and I tested it pretty thoroughly.

**Comment by williambr** [comment]
I don't understand, how is the journal feature dependent on the pipe change calls?
I cannot make sense why you can't do it with _pipeopen. Doesn't it just goes back in the traceback stack and get the caller of the method? What makes it impossible without changing the API it the way you did?

**Comment by williambr** [comment]
I mean, of course you wont be able to catch the exception, but there is already a log.debug which can be used to that effect. You wont get that return code of course but seems useful enough.

**Comment by williambr** [comment]
Oh screw it, I'll merge this, if anything break I'll hunt you hahaha, just kidding ;)

**Comment by williambr** [comment]
Now that you said you have tested it very thoroughly please tell me why some process are stuck, in zombie state:

e.g.: python /usr/local/www/freenasUI/middleware/notifier.py restart webshell

**Comment by fhriley** [comment]
I was unaware of this avenue of testing. I was testing with the GUI. Are there any other ways to test this code? Or would you rather outside people not be contributing to the code?

**Comment by jordanhubbard** [comment]
We are actually thrilled when outside people contribute to the code.  A major portion of the FreeNAS 10 refactoring, redesign and developer's guide is aimed specifically at outside people contributing to the code.  The FreeNAS 9.3 code, however, is not easy to hack (as you found out) and requires fairly substantial testing from a variety of angles to avoid breaking it because things are so intertwined and fragile.  Now you perhaps better understand my reluctance and initial concerns about regressions a bit better?  It wasn't personal, it was driven purely by bitter experience.  To hack on the middleware, you have to be a bit of a python ninja, and of course python ninjas test the code *first* directly in python, only moving to the GUI from there when they are sure everything is working at the lower levels.

**Pull request closed without merging**
