### PR TITLE
- If we can't reserve memory from ZFS ARC for a guest VM,

### PR DESCRIPTION
**Pull request by araujobsd**
we need to let the upper layer knows about it.

Ticket: #34825

### CODE REVIEW

**Comment by araujobsd** [comment]
@themylogin I cannot call `raise CallError` on `__init_guest_vmemory` because I need a return value on `def start` to be able to know if the memory was reserved or not. Or am I missing something?

**Comment by themylogin** [comment]
@araujobsd you can (and you should) raise it in there and you should propagate this exception to the client in `start`

**Comment by themylogin** [comment]
@araujobsd `start` behavior has not changed. Just remove all exception handling from there.

**Comment by themylogin** [comment]
@araujobsd also `===> ` should not be in the message that users see

**Comment by araujobsd** [comment]
@themylogin There are other parts that need to be reworked, this is the safest way at this stage to return an errno related with memory allocation resource problem. Thanks for the review.

**Comment by ericbsd** [comment]
I just learn that we need to approval of @dlavigne.  Too late!

**Comment by araujobsd** [comment]
So please, somebody else remember to merge this one... Thanks!

**Comment by araujobsd** [comment]
So, I'm restoring the branch.

**Pull request merged**
