### PR TITLE
Allow catia to be added independently from fruit, still maintaining t…

### PR DESCRIPTION
**Pull request by kmoore134**
…he right modules order where appropriate

Ticket: #26558

### CODE REVIEW

**Comment by b-a-t** [comment]
Jenkins, retest this please

**Comment by b-a-t** [comment]
Jenkins, retest this please CLEAN

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by b-a-t** [comment]
Jenkins, retest this please CLEAN

**Comment by b-a-t** [comment]
Jenkins, retest this please CLEAN

**Pull request merged**
