### PR TITLE
unlock SED on boot

### PR DESCRIPTION
**Pull request by jpaetzel**
https://redmine.ixsystems.com/issues/28592

### CODE REVIEW

**Comment by jpaetzel** [comment]
That Travis CI failure is due to an increased count (2) in flake complaints.  I checked all python files with flake before commiting, the only flake errors this pull request introduces are a line to long error in each of the database migration files of which there are two migrations.  (which those are autogenerated with django and the line too long flake error exists in nearly every migration file there is)

Is fixing FreeNAS flake errors the cost of doing business these days??? :)

**Comment by jpaetzel** [comment]
Post stage
[0:11:22] ==> Installing ports
[0:11:22] ==> Log file: /freenas-pipeline/freenas/_BE/objs/logs/pkg-install
[0:37:35] ==> ERROR: Packages installation failed, see log file /freenas-pipeline/freenas/_BE/objs/logs/pkg-install
*** Error code 1

Looks like the failure has nothing to do with this pull request.

**Comment by william-gr** [comment]
You have a conflicting system migration, thats why its failing on install. Two 0010 migrations iirc.

**Comment by william-gr** [comment]
@jpaetzel not to be picky about it but I suppose you have to also rename the dependency name within it, or it will still break (not 100% sure though)

**Comment by jpaetzel** [comment]
[00:00:14] Starting jail ja-p
[00:00:14] Logs: /freenas/git/freenas-build/freenas/_BE/objs/ports/data/logs/bulk/ja-p/2018-02-20_07h39m42s
[00:00:14] Loading MOVED
[00:00:14] Ports supports: DEPENDS_ARGS SELECTED_OPTIONS
[00:00:14] Gathering ports metadata
[00:00:14] Error: Nonexistent origin listed for build: freenas/freenas-webui
[00:00:14] Error: Nonexistent origin listed for build: freenas/py-libzfs
[00:00:14] Error: Fatal errors encountered gathering initial ports metadata
[00:00:14] Cleaning up
[00:00:14] Unmounting file systems
[0:02:41] ==> ERROR: Ports build failed
[0:02:41] ==> Cleaning up poudriere environment...
[0:02:41] ==> Unmounting ports overlay...
*** Error code 1

Stop.
make[2]: stopped in /freenas/git/freenas-build
*** Error code 1

Stop.
make[1]: stopped in /freenas/git/freenas-build
*** Error code 1

Stop.
make: stopped in /freenas/git/freenas-build

For what it's worth my local build fails as well.

**Comment by jpaetzel** [comment]
I swear I used to know how database migrations work.

**Pull request merged**
