### PR TITLE
Short and sweet 

### PR DESCRIPTION
**Pull request by sambonham**

### CODE REVIEW

**Comment by williambr** [comment]
Why was this merged? It has essentially no changes.

One commits changes, and the next one reverts the change.

**Comment by dlavigne** [comment]
I have discussed this with Sam and she knows what she did wrong in her workflow. A proper commit will happen soon.

Cheers,

Dru

--------------------------------------------
On Mon, 5/2/16, William Grzybowski <notifications@github.com> wrote:

 Subject: Re: [freenas/freenas] Short and sweet  (#141)
 To: "freenas/freenas" <freenas@noreply.github.com>
 Cc: "Dru Lavigne" <dru.lavigne@att.net>, "State change" <state_change@noreply.github.com>
 Date: Monday, May 2, 2016, 1:57 PM
 
 Why was this merged? It has
 essentially no changes.
 
 One commits changes, and the next one reverts the
 change.
 
 —
 You are receiving this because you modified the open/close
 state.
 Reply to this email directly or view
 it on GitHub

**Comment by vaibhav-rbs** [comment]
please commit your changes after I announce code unfreeze.

**Comment by Arcanemagus** [comment]
@dlavigne The point isn't what @sambonham did, but the fact that you merged two commits that, in summation, make absolutely no change.

Unless you are saying that @sambonham used your account to merge this?

**Comment by chris3torek** [comment]
I agree with both @williambr and @Arcanemagus here, the two commits just wind up being noise.

I'm not sure what we use for standard practice for these repositories and the various pull requests, but just on general principles I would only keep a "bad idea" commit (one that gets reverted or is undone later) in history if (a) it's too late to remove it—i.e., we already put it in and people have grabbed it and now we *have* to undo it as a separate commit, or (b) it's educational, in the sense of "please don't do this, it seemed like a good idea but we tried and it failed".  Otherwise (as in this case) I'd just reject / retract the pull request entirely and replace it with a new one with one or more "good" commits instead...

**Pull request merged**
