### PR TITLE
Include smbstatus -L output in debug

### PR DESCRIPTION
**Pull request by anodos325**

### CODE REVIEW

**Comment by agokhale** [comment]
lgtm; he proposed it wrote it; patch looks safe

**Comment by agokhale** [comment]
lgtm

**Comment by agokhale** [comment]
Jenkins please retest this.

**Comment by kmoore134** [comment]
Jenkins: add to whitelist

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by anodos325** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
retest

**Pull request merged**
