### PR TITLE
feat(gui): add reporting plugin for cpu temperature(s)

### PR DESCRIPTION
**Pull request by dnandha**
I'm adding a plugin to the gui reporting page which displays a graph for cpu core temperatures. The cpu temperature data is already provided as a set of rrd files by the freenas os - so why not visualize these, right?

### CODE REVIEW

**Comment by kmoore134** [comment]
Ok to test

**Comment by dnandha** [comment]
Jenkins: Retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by dnandha** [comment]
Re-Opened with shorter branch name in #317

**Pull request closed without merging**
