### PR TITLE
tkt-60219: Allow middleware to control swap mirroring on boot disks

### PR DESCRIPTION
**Pull request by freqlabs**
(11.2 version of of #2278)

Prevents needless synchronization of swap mirror on unclean boot.

Ticket: #60219

### CODE REVIEW

**Comment by william-gr** [comment]
So what will happen with people before this? They will continue to have gmirror with broken sync until they reinstall?

**Comment by freqlabs** [comment]
If we intend to keep existing mirrors labeled for booting into old bootenvs, then perhaps middleware could run `gmirror configure -F swap` to set NOFAILSYNC on automatic mirrors to fix that.

**Comment by william-gr** [comment]
That would require the code to exist for many years in middleware because of a mistake in installer code.

**Comment by freqlabs** [comment]
I'm not familiar with how updates work, but it maybe an update is a better place to make that change then.

**Pull request merged**
