### PR TITLE
fix(snmp): Quiet freenas-snmpd.py

### PR DESCRIPTION
**Pull request by darkfiberiru**
Ticket: #26484

### CODE REVIEW

**Comment by william-gr** [comment]
I think it would be better to log it somewhere, even if a lower priority, in debug.log

**Comment by darkfiberiru** [comment]
This goes away in 11.1 with replacement of snmp backend. We can have it also dump to daemon instead of messages but that will just at this point cause the same issue where it is causing historical entries in whichever log file to rollover and disappear on systems that have snmp access happening.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by william-gr** [comment]
Jenkins retest this please

**Comment by william-gr** [comment]
@darkfiberiru if snmpd breaks how will you catch the cause then?

**Pull request closed without merging**
