### PR TITLE
Initial error message review

### PR DESCRIPTION
**Pull request by Mrt134**
Per request - I've reviewed and done some slight reworks to error messages in an effort to have them be more communicative or prevent reader confusion.

### CODE REVIEW

**Comment by william-gr** [comment]
You need to be careful with python, tabs vs spaces matter, also how lines are broken may raise PEP8 issues that wont pass Travis CI.

**Comment by Mrt134** [comment]
Ok, I'll review it more carefully and update the PR.

**Comment by Mrt134** [comment]
I'll keep trying; I'm learning as I go. :P

**Comment by william-gr** [comment]
@Mrt134 the lines starting with `+` are the new problems you have introduced: https://travis-ci.org/freenas/freenas/builds/356948076?utm_source=github_status&utm_medium=notification

**Comment by Mrt134** [comment]
Thanks, I'll review those and keep trying.

**Pull request merged**
