### PR TITLE
Make `Default permissions` checked when we create a share 

### PR DESCRIPTION
**Pull request by b-a-t**
and unchecked when we edit it.

### CODE REVIEW

**Comment by jhixson74** [comment]
Another consideration is when a new share is created for something that used to be a share. We don't want to auto reset the permissions in these cases. That is how it formerly worked, however, since this is being reworked, let's fix it!

**Comment by b-a-t** [comment]
On the first comment: that was my exact understanding and I hope, that's how I implemented it. When you create new share - the checkbox `Default permissions` is checked, when we edit existing share - the checkbox is un-checked.

**Comment by b-a-t** [comment]
For the second comment: if we have a way to distinct such a situation - sure, we can code it :)

Another thing is that Django is already declared obsolete :), so there is no point to make it perfect. It's still used as a REST API backend, so let's implement business logic there now, while GUI can be altered on Angular side.

**Comment by jhixson74** [comment]
If it does what you say it does then all is well. As for django being obsolete, the new UI is not ready yet and TrueNAS will continue to use it until it's ready even after released for FreeNAS. I think it's safe to say we have to support it for a minimum of one more year if not more.

**Pull request merged**
