### PR TITLE
Create global variable `is_truenas` to reduce number of client calls.

### PR DESCRIPTION
**Pull request by b-a-t**
Use `is_truenas` to determine the location of the `privatedir`.

### CODE REVIEW

**Comment by b-a-t** [comment]
We don't really care about HA part here, but OK, renamed according to the comment.

**Comment by b-a-t** [comment]
I'm not sure that we really need this block anymore, but leave it ATM:
```
     if not os.access("/var/db/samba4/private", os.F_OK):
         smb4_mkdir("/var/db/samba4/private")
         os.chmod("/var/db/samba4/private", 0o700)
```

**Comment by william-gr** [comment]
What do you mean we dont care about HA? Please elaborate.

**Comment by b-a-t** [comment]
In this particular patch and script we just trying to distinct FreeNAS and TrueNAS, not really taking HA into account. There is one place in the code, where we do care on which side of the HA fence we are, but that's not affected by this fix.

**Comment by william-gr** [comment]
@b-a-t that makes no sense to me. We *only* care about HA, not just truenas. Thats what "failover_licensed" means.

**Pull request merged**
