### PR TITLE
Be more thorough in logging commands

### PR DESCRIPTION
**Pull request by fhriley**
I left this in two commits so the diffs can be seen. Let me know if you want me to rebase to one commit.

### CODE REVIEW

**Comment by williambr** [comment]
Well, I might be wrong since I didn't write that code, but I was under the impression that the python/django process masked the signals and the intent with sigprocmask was to remove the mask in the forked process (since by default it is inherited?).

I'll have to test/analyze it more thoughtfully before merge it.

**Comment by williambr** [comment]
But again, since django runs in threaded move I believe pthread_sigmask should have been used so I doubt it has any effect.

**Comment by fhriley** [comment]
If you want me to put it back, let me know, although I agree it should be using the threaded version. I believe everything else should be working fine.

**Comment by fhriley** [comment]
Any status on this? There's a [guy in the forum](https://forums.freenas.org/index.php?threads/unable-to-gpt-format-the-disk-ada0.28761/#post-188638) whose problem could be easily diagnosed with this code.

**Comment by jordanhubbard** [comment]
So, just to make sure we’re on the same page - did you address the earlier issues that caused FreeNAS to not work, and did you also test them in the manner that William outlined before (calling python directly on various middleware methods) to make this safe to pull again?   Thanks.

- Jordan

**Comment by fhriley** [comment]
Yes.

**Pull request closed without merging**
