### PR TITLE
NAS-108637 / 20.12 / Set 120 character pep8 line limit

### PR DESCRIPTION
**Pull request by sonicaj**
This commit changes max character limit to 120 keeping in line with what we have had before.

### CODE REVIEW

**Review by yocalebo — COMMENTED** [review]
This looks good to me, however, do we know why pep3speaks is still complaining about line length when it's clearly in the `ignore:` section?

**Comment by sonicaj** [comment]
Not sure, if we search to see how to disable the 80 char limit, this is what comes up for pep3speaks. So we probably need these 2 to make sure it's respected.

**Review by yocalebo — APPROVED** [review]
Just makes me wonder if the other items in the ignore list are correct.

**Review by william-gr — APPROVED** [review]

**Comment by william-gr** [comment]
Try using the other checker, instead of flake8

**Comment by william-gr** [comment]
@sonicaj

**Pull request closed without merging**
