### PR TITLE
Certificate chain saved correctly.

### PR DESCRIPTION
**Pull request by jatinder-kumar-calsoft**
Ticket: #9879

### CODE REVIEW

**Comment by surajrav** [comment]
Gimme till tmrw to go through this and review it properly. In the meanwhile I still own this ticket on redmine. Tried transferring it to you but do not see your account listed in the assignee list, working on fixing that.

**Comment by surajrav** [comment]
Hi Jatinder I went through your commit and it is correct.

However I have some suggestions to make:
    1. Since this function is used both in `CertificateImportForm` as well as `CertificateAuthorityImportForm` please make it a common routine that these forms can then call or something in a similar fashion that avoids code duplication.
    2. Just as a good practice we can do this regex compile: `regex = re.compile(r"(-{5}BEGIN[\s\w]+-{5}[^-]+-{5}END[\s\w]+-{5})+", re.M | re.S)` completely outside this function (i.e. globally) such that it does not have to be done each time the function is called.
    3. While you are implementing this might as well implemet cert chain and cert public key to private key validation. I own a ticket for that over at bugs.freenas.org, I will hand it over to you today with proper comments regarding what to do. I think the code changes for that ticket would also go in this very function itself so it should be relatively easy.

Thanks.

**Comment by surajrav** [comment]
btw I just remembered that this regex is already defined in gui/common/ssl.py as `CERT_CHAIN_REGEX` so you can just import it form there.

**Comment by jatinder-kumar-calsoft** [comment]
After going through the code, I found many redundant functions that are not part of my commit.
For reg.
In class, **CertificateAuthorityImportForm** , **CertificateAuthorityCreateInternalForm,** **CertificateImportForm,** **CertificateImportForm** and **CertificateImportForm have** **clean_cert_name** function. 
To address this situation
 Create new "parent base class" which will have all the functions and later can drive
the new classes from the parent class. This needs change in complete design of the code and requires lot of testing.

**Comment by surajrav** [comment]
For now lets just implement any new functions going forward as non redundant was my point.
 
We can worry about removing the rest of the redundancy later. Also the certificate base class was also implemented in system/models.py

**Comment by jatinder-kumar-calsoft** [comment]
I have tried to cut  the code duplication by calling **def check_certificate**  function from class **CertificateAuthorityImportForm** and class **CertificateImportForm** classes . 
```
def check_certificate(certificate):
    regex = re.compile(r"(-{5}BEGIN[\s\w]+-{5}[^-]+-{5}END[\s\w]+-{5})+", re.M | re.S)
    matches = regex.findall(certificate)

    nmatches = len(matches)
    if not nmatches:
        raise forms.ValidationError(_(
            "Not a valid certificate."
        ))

    return certificate,nmatches
```
```
class CertificateAuthorityImportForm(ModelForm):

-----------
def clean_cert_certificate(self):
        cdata = self.cleaned_data
        certificate = cdata.get('cert_certificate')
        if not certificate:
            raise forms.ValidationError(_("Empty Certificate!"))
        certificaten,nmatches = check_certificate(certificate)
    
        if nmatches > 1:
            self.instance.cert_chain = True
        #
        # Should we validate the chain??? Probably
        # For now, just assume the user knows WTF he is doing
        #
        
        return certificate
-----------
```

**Comment by surajrav** [comment]
Issue #165 solves this in a much better manner. Closing this to test and accept that instead

**Pull request closed without merging**
