### PR TITLE
tkt-78843: Remove RancherOS and add Grub boot loader support

### PR DESCRIPTION
**Pull request by william-gr**

### CODE REVIEW

**Comment by skarekrow** [comment]
:champagne:

**Comment by william-gr** [comment]
Timed out on waiting docs team to review this, merging anyway.

**Comment by dlavigne** [comment]
Hmm, doesn't look like docs was invited to the PR? Adding now.

**Comment by william-gr** [comment]
@dlavigne if you look at the logs yes they were, I removed after merging.

**Pull request merged**
